### ISSUE TITLE
The application is not treating all user equally

### ISSUE THREAD

**Issue by arturolszak** [martinskuta/InnoveoBabyfoot#1]
Hi,

I believe something is wrong there… It looks like the application is coded in a way that makes me always the last ;)
Now seriously… I was trying to find the query string that fits me best (reflects my achievements), and… I set the following criteria:

http://babyfoot.neocities.org/?from=18.04.2016&to=18.04.2016&minNrOfGames=1

On that day (18.04), there was just one game (which I obviously won ;). But still… I am at the bottom of the list – last!! (user Artur).

**Comment by martinskuta** [comment]
It is fixed!
